### ISSUE TITLE
cant submit this

### ISSUE THREAD

**Issue by codewithxavi** [xavimondev/hubdev.tools#17]
![image](https://github.com/user-attachments/assets/c00b84cc-fe31-47c5-a564-8b8a7bd72594)
![Captura de pantalla 2024-10-22 115226](https://github.com/user-attachments/assets/eed2c1df-1a1f-490b-96e0-57bdf6574991)

**Comment by xavimondev** [comment]
Hola! Gracias por reportar 💯, la razón es por una regla de validación que evita agregar sitios con que incluyen dominio google.com para evitar algún posible spam. Le daré una revisada a la regla para evitar este tipo de errores.
